import React from "react";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import StyledComponentsRegistry from "../lib/AntdRegistry";
import ThemeConfigProvider from "@/config/ThemeConfig";
import MainLayout from "@/layouts/MainLayout";
import FormProvider from "@/contexts/form.context";
import ProviderQueryClient from "@/config/QueryClientConfig";

const inter = Inter({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <ThemeConfigProvider>
        <StyledComponentsRegistry>
          <ProviderQueryClient>
            <FormProvider>
              <MainLayout>{children}</MainLayout>
            </FormProvider>
          </ProviderQueryClient>
        </StyledComponentsRegistry>
      </ThemeConfigProvider>
    </body>
  </html>
);

export default RootLayout;
