trigger:
- main

resources:
- repo: self

pool: 
  vmImage: $(vmImageName)

stages:
- stage: Build
  jobs:
  - job: Docker_build_push
    steps:
    - task: Docker@2
      displayName: Build & Push Docker Image  
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        